apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-d-prod-config
  namespace: exam-4 # Trainee Dave's assigned namespace
data:
  # Contains Production-specific text
  config.json: |
    {
      "app_name": "portal-d",
      "subtitle": "Production Environment",
      "owner": "Dave"
    }
