apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-d-prod
  namespace: exam-4
spec:
  replicas: 1 # Number of pods to run
  selector:
    matchLabels:
      app: portal-d-prod # Links the deployment to the production pods it creates
  template:
    metadata:
      labels:
        app: portal-d-prod
    spec:
      imagePullSecrets:
      - name: regcred # Authentication for pulling from the private registry
      containers:
      - name: portal-d-prod
        # Jenkins will dynamically replace IMAGE_TAG_PLACEHOLDER with the real tag
        image: 192.168.10.23:5000/portal-d:v1.1.0
        ports:
        - containerPort: 5000 # The port our Flask app is listening on
        env:
        # Sets APP_ENV to Production
        - name: APP_ENV
          value: "production"
        - name: APP_VERSION
          value: v1.1.0 # APP_VERSION
        - name: CONFIG_PATH
          value: "/app/config/config.json"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: portal-d-prod-secret # Matches the name in secret.yaml
              key: API_KEY
        # Maps the Production ConfigMap into the container
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        resources:
          # Minimum resources guaranteed to the pod
          requests:
            memory: "64Mi"
            cpu: "50m"
          # Maximum resources the pod is allowed to use
          limits:
            memory: "128Mi"
            cpu: "100m"
        # Health probes
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 10
      volumes:
      - name: config-volume
        configMap:
          name: portal-d-prod-config # Matches the name in configmap.yaml
