apiVersion: v1
kind: Service
metadata:
  name: portal-d-prod-service
  namespace: exam-4
spec:
  type: NodePort # Exposes the service on a static port on the cluster nodes
  selector:
    app: portal-d-prod # Routes traffic to production pods only
  ports:
    - port: 5000 # The port inside the cluster
      targetPort: 5000 # The port on the container
      nodePort: 30184 # Trainee Dave's assigned NodePort for Production
