apiVersion: v1
kind: Service
metadata:
  name: portal-d-service
  namespace: exam-4
spec:
  type: NodePort
  selector:
    app: portal-d
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30184
